version: "3.8"

services:
  web:
    build: .
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 3306; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080
      "
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=myproject
      - DJANGO_DB_USER=django_user
      - DJANGO_DB_PASSWORD=django_password

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=myproject
      - MYSQL_USER=django_user
      - MYSQL_PASSWORD=django_password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3306:3306"

volumes:
  mysql_data:
